### ISSUE TITLE
[Bug] Completed match doesn't get update on admin side

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#138]
**Describe the bug**
I'm a player on round 2 and I submit a score to give the opponent a win so this match has been completed, but when looking at the admin side there are no score showing and the status of the match is still in ready up phrase

**To Reproduce**
1. I set up a tournament 
2. I start round 2 without finalizing round 1
3. I ready up both my account, and 1 account give a win to another account
4. The match went completed, I can see the final scores on my match page, and also see the bracket/schedule update with this result
5. Then I look at the admin side, this match still have no score and still in ready up phrase

**Expected behavior**
Match scores should be updated real time once the match is finalized

**Screenshots**
![image](https://github.com/edosdigital/issues/assets/151843786/a42fe918-ecac-406a-95bf-39e6f6025799)

## Tournament URL/ID
https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Manage?tournamentId=4gv0r16029r4a03sv09byc555q

**Comment by AydinE** [comment]
I think this was related to something else, please verify if fixed

**Comment by EJNiones** [comment]
Issue is fixed:

https://gyazo.com/9e4c687a0af9d8eadb4eece8edf1d3f6

**Comment by JayWongjedjan** [comment]
Reported from Kimoy as the admin side is still not update the result real-time after match scores have been finalized from FE
https://drive.google.com/file/d/1NFA3Tb7TERsTroOzRAnuA9fFccvQqxWp/view
